# Please see the following for configuration options:
#   https://github.com/bbatsov/rubocop
#   https://github.com/nevir/rubocop-rspec
require: rubocop-rspec

AllCops:
  RunRailsCops: true

Documentation: false
